### PR TITLE
Closes #1378 - Preserve whitespaces in Configuration Docs

### LINKED ISSUE #1378: [Bug] Whitespaces in descriptions are collapsed in config-docs
**Describe the bug**
Any whitespaces in descriptions in config-docs are collapsed to one whitespace leading to unreadable descriptions like the one in the screenshot.

**To Reproduce**
1. Go into config-server UI.
2. Open config-docs.
3. Select Default Mapping.
4. Search for a_regex_replaceAll_multi

image

**Expected behavior**
Preserve whitespaces to look like:
image

### PR DESCRIPTION
**Pull request by aaronweissler**
Closes #1378

---
This change is [Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1379)

### CODE REVIEW

File: components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js [hunk 1]
```diff
@@ -25,6 +25,7 @@ const BaseDocsElement = ({ data, type, registerRef, scrollTo }) => {
           padding: 0.5rem;
           transition: background-color 0.2s;
           border-bottom: solid 1px #eeeeee;
+          white-space: pre-wrap
```
Comment (aaronweissler) [inline components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js]: Depending on if this should only be possible for the main 'description' or for example also for descriptions of inputs in actions, the CSS statement could also be moved to .description instead of the whole .element

File: components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js [hunk 2]
```diff
@@ -25,6 +25,7 @@ const BaseDocsElement = ({ data, type, registerRef, scrollTo }) => {
           padding: 0.5rem;
           transition: background-color 0.2s;
           border-bottom: solid 1px #eeeeee;
+          white-space: pre-wrap;
```
Comment (aaronweissler) [inline components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js:28]: Depending on if this should only be possible for the main 'description' or for example also for descriptions of inputs in actions, the CSS statement could also be moved to .description instead of the whole .element

**Review by mariusoe — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1379)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler)

___
*[components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js, line 28 at r1](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1379#-MztIcsdOAu2OkBmaqPV-r1-28:-MzynzF23RDjDL7Pypm2:bj79fq) ([raw file](https://github.com/inspectit/inspectit-ocelot/blob/4b88573038e8c57877cdb4d44bae8c28dc4ce465/components/inspectit-ocelot-configurationserver-ui/src/components/views/configuration/documentation/BaseDocsElement.js#L28)):*
<details><summary><i>Previously, aaronweissler wrote…</i></summary><blockquote>

Depending on if this should only be possible for the main 'description' or for example also for descriptions of inputs in actions, the CSS statement could also be moved to .description instead of the whole .element
</blockquote></details>

Let's keep the formatting only in the description. The documentation of the individual elements should not contain large blocks of text. If they do, they should be in the description, as we discussed.

I just commited the change, so this PR is done.

**Review by mariusoe — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/inspectit/inspectit-ocelot/1379)* status: all files reviewed, 1 unresolved discussion (waiting on @aaronweissler)
